GET https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
Content-Type: application/json
X-goog-api-key: imnotanidiot

{
  "contents": [
    {
      "parts": [
        {
          "text": "Explain how AI works in a few words"
        }
      ]
    }
  ]
}