spring.application.name=career-builder
gemini.api.key=${GOOGLE_API_KEY}
job.hunt.spreadsheet.location=C:/Users/frafr/Downloads/job_tracker.xlsx
google.api.key=${GOOGLE_API_KEY}
webhook.secret=${WEBHOOK_SECRET}


career.builder.webhook.username=${CAREER_BUILDER_WEBHOOK_USERNAME}
career.builder.webhook.token=${CAREER_BUILDER_WEBHOOK_TOKEN}


# 1. The URL must NOT contain the username and password tokens inside it!
# Cut everything between the '//' and the '@' symbol out of your string.
spring.datasource.url=${SPRING_DATASOURCE_URL}

# 3. Explicitly declare the driver
spring.datasource.driver-class-name=org.postgresql.Driver
