spring.application.name=career-builder
gemini.api.key=stillnotstupid
job.hunt.spreadsheet.location=C:/Users/frafr/Downloads/job_tracker.xlsx
google.api.key=${GOOGLE_API_KEY}
webhook.secret=${WEBHOOK_SECRET}