package dev.chrishful.career.builder.tools;

import com.google.adk.tools.Annotations.Schema;
import com.google.adk.tools.FunctionTool;
import dev.chrishful.career.builder.dto.JobApplicationDto;
import org.apache.poi.ss.usermodel.*;
import org.springframework.stereotype.Component;

import java.util.Map;

import dev.chrishful.career.builder.service.DatabaseService;

import java.util.Collections;
import java.util.List;

@Component
public class JobTrackerTool {

    private final DatabaseService databaseService;

    public JobTrackerTool(DatabaseService databaseService) {
        this.databaseService = databaseService;
    }

    @Schema(description = """
            Adds a new job application or updates an existing one in the SQL job tracker database.
            Call this whenever the user mentions applying somewhere, a rejection, an interview,
            withdrawing, or any status change. Updates the record in place if company exists, inserts if new.
            """)
    public Map<String, String> updateJobTracker(
            @Schema(description = "Company name") String company,
            @Schema(description = "Job title / role") String role,
            @Schema(description = "Status: Applied, Rejected, Phone Screen, Interview, Withdrawn") String status,
            @Schema(description = "Interest level: YES, No, Maybe. Null if unknown.") String interested,
            @Schema(description = "Salary estimate e.g. '$130k-160k'. Null if unknown.") String salaryEst,
            @Schema(description = "Remote: Yes, No, or null if unknown.") String remote,
            @Schema(description = "Date applied MM/dd/yyyy. Defaults to today if null.") String dateApplied,
            @Schema(description = "Any notes. Null if none.") String notes
    ) {
        System.out.println("updateJobTracker SQL pipeline called for: " + company);

        try {
            // Normalize inputs for database matching
            boolean isRemoteField = "Yes".equalsIgnoreCase(remote);
            String normalizedStatus = normalizeStatus(status);

            // Construct the payload DTO
            JobApplicationDto dto = new JobApplicationDto(
                    null, // UUID auto-generated by DB
                    0,    // display number auto-assigned by DB
                    company,
                    role != null ? role : "",
                    dateApplied, // Passed down if present, else DB defaults to CURRENT_DATE
                    normalizedStatus,
                    interested != null ? interested : "Maybe",
                    salaryEst != null ? salaryEst : "",
                    isRemoteField,
                    null, // lastUpdated handled by DB timestamp trigger
                    notes != null ? notes : ""
            );

            // Execute database upsert logic
            String resultMessage = databaseService.upsertApplicationByCompanyAndRole(dto);

            return Map.of("status", "success", "message", resultMessage);

        } catch (Exception e) {
            System.err.println("Database execution tracking fault: " + e.getMessage());
            return Map.of("status", "error", "message", e.getMessage());
        }
    }

    @Schema(description = "Retrieves recent job application records from the database for historical progress reporting.")
    public List<JobApplicationDto> getJobTrackerEntries(
            @Schema(description = "Lookback window in days (e.g. 1 for today, 7 for this week, 30 for last month)") int lookbackDays) {
        try {
            return List.of();
            //return databaseService.getApplicationsWithLookback(lookbackDays);
        } catch (Exception e) {
            System.err.println("Failed to fetch history metrics: " + e.getMessage());
            return Collections.emptyList();
        }
    }

    public void updateJobTracker(JobApplicationDto dto) {
        updateJobTracker(
                dto.company(),
                dto.role(),
                dto.status(),
                dto.interested(),
                dto.salaryEstimate(),
                dto.remote() ? "Yes" : "No",
                dto.dateApplied(),
                dto.notes()
        );
    }

    public FunctionTool asTool() {
        return FunctionTool.create(this, "updateJobTracker");
    }

    private String normalizeStatus(String rawStatus) {
        if (rawStatus == null || rawStatus.isBlank()) return "Applied";
        // Map common variations to your strict check constraints (Applied, Interview, Rejected)
        String lower = rawStatus.toLowerCase();
        if (lower.contains("reject") || lower.contains("pass")) return "Rejected";
        if (lower.contains("interview") || lower.contains("screen")) return "Interview";
        return "Applied";
    }
}